apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432 #source port
      targetPort: 5432

  selector:
    name: postgres-pod #labels from the Pod/ list of filters
    app: demo-voting-app



