apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379 #source port
      targetPort: 6379

  selector:
    name: redis-service #labels from the Pod/ list of filters
    app: demo-voting-app


