---
applications:
- name: mysqlefcore-connector
  buildpacks:
   - dotnet_core_buildpack
  memory: 256M
  disk_quota: 600M
  #command: cd ${HOME} && ./MySqlEFCore
  env:
    ASPNETCORE_ENVIRONMENT: Development
  services:
   - myMySqlService1
  # - myOtherMySqlService
